---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: base-deploy
  namespace: k3s-base
  labels:
    app: base
spec:
  replicas: 1
  selector:
    matchLabels:
      app: base
  template:
    metadata:
      labels:
        app: base
    spec:
      containers:
        - name: base
          image: traefik
          ports:
            - name: base
              containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: base-svc
  namespace: k3s-base
  labels:
    service: base
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      protocol: TCP
  selector:
    app: base
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: base-ingress
  namespace: k3s-base
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  rules:
    - http:
        paths:
          - path: /test
            pathType: Prefix
            backend:
              service:
                name: base-svc
                port:
                  number: 80