---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: codeserver-pvc
  namespace: codeserver
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: codeserver-deployment
  namespace: codeserver
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: codeserver
  template:
    metadata:
      labels:
        app: codeserver
    spec:
      containers:
        - name: codeserver
          image: linuxserver/code-server
          ports:
            - containerPort: 8443
          volumeMounts:
            - name: codeserver-pvc
              mountPath: /config
      volumes:
        - name: codeserver-pvc
          persistentVolumeClaim:
            claimName: codeserver-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: codeserver-service
  namespace: codeserver
spec:
  type: ClusterIP
  ports:
    - name: http
      targetPort: 8443
      port: 8443
      protocol: TCP
  selector:
    app: codeserver
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: codeserver-ingress
  namespace: codeserver
spec:
  entryPoints:
    - web
  routes:
    - match: PathPrefix(`/codeserver`)
      kind: Rule
      services:
        - name: codeserver-service
          kind: Service
          port: 8443
