---
name: shellcheck

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  lint:
    name: Lint

    runs-on: ubuntu-latest

    steps:
      - name: Check out the codebase
        uses: actions/checkout@v3

      - name: Run shellcheck
        run: |
          shellcheck --version
          grep -rl '^#!/.*sh' * | xargs -n1 shellcheck -x
